["Heroku"]
description = "Heroku is a cloud platform that lets companies build, deliver, monitor and scale apps — we're the fastest way to go from idea to URL, bypassing all those infrastructure headaches."
website= "https://www.heroku.com"

["Codepen"]
description = "An online code editor, learning environment, and community for front-end web development using HTML, CSS and JavaScript code snippets."
website = "https://codepen.io/"

["JSFiddle"]
description = "An online code editor, learning environment, and community for front-end web development using HTML, CSS and JavaScript code snippets."
website = "https://jsfiddle.net/"
contributor = "@emrivero"
type = "tool"

["CheckIO"]
description = "Coding games for beginners and advanced programmers where you can improve your coding skills by solving engaging challenges and fun task using Python and JavaScript."
website = "https://checkio.org/"
contributor = "@emrivero"
type = "tool"

["CodeWars"]
description = "Codewars is where developers achieve code mastery through challenge. Train on kata in the dojo and reach your highest potential."
website = "https://www.codewars.com/"
contributor = "@emrivero"
type = "tool"

["W3Schools"]
description = "W3Schools is an educational website for learning web technologies online"
website = "https://www.w3schools.com/"
contributor = "@emrivero"
type = "tutorial"

["freeCodeCamp"]
description = "freeCodeCamp is a non-profit organization that consists of an interactive learning web platform, an online community forum, chat rooms, online publications and local organizations that intend to make learning web development accessible to anyone"
website = "https://www.freecodecamp.org/"
contributor = "@emrivero"
type = "codecamp"


["Codesignal/Codefights"]
description = "Learn how you can go beyond resumes in technical hiring with a state-of-the-art assessment platform and advanced coding tests."
website = "https://app.codesignal.com/"

["Scrimba"]
description = "Scrimba lets you play around with the instructor's code directly inside the screencast. As a result, you'll learn faster and have more fun."
website = "https://scrimba.com/"
type = "tutorial"


["HTTP Status Codes definitions"]
description = "This page is created from HTTP status code information found at ietf.org and Wikipedia."
website = "https://www.restapitutorial.com/httpstatuscodes.html"
contributor = "@glopez97"
type = "reading"

["BOTO3 Documentation"]
description = "Boto docs in a glimpse"
website = "https://boto3.amazonaws.com/v1/documentation/api/latest/index.html"
contributor = "@glopez97"
type = "reading"

["Mattermost"]
description = "Slack but opensource"
website = "https://mattermost.com/"
contributor = "@glopez97"
type = "tool"

["Typora"]
description = "Minimalistic markdown editor"
website = "https://typora.io/"
contributor = "@glopez97"
type = "tool"
