name: Updating readme file
on:
  pull_request:
    types: [labeled]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Intalling NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: building README.md
        run: |
          npm install
          npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto updates README.md