name: Updating readme file
on:
  pull_request_review:
    types:
      - submitted
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: building README.md
        run: |
          npm install
          npm run build
      - name: automerge
      - uses: squalrus/merge-bot@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test: true
          reviewers: true
          labels: automerge
          blocking_labels: no-merge
          checks_enabled: true
          method: squash
          delete_source_branch: true
