name: Updating readme file
on:
  pull_request_review:
    types: [submitted]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Intalling NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: building README.md
        run: |
          npm install
          npm run build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "AUTOGEN README"
      - name: Creating PR
        uses: peter-evans/create-pull-request@v3
            base: master