name: Updating readme file
on:
  pull_request:
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
        with:
          ref: master
      - name: using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: building README & CONTRIBUTING .md
        run: |
          npm install
          npm run build
      - name: Adding new goodies...
        uses: mikeal/publish-to-github-action@master
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
