name: Updating readme file
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 11.x]
    steps:
      - uses: actions/checkout@v1
      - name: using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: building README & CONTRIBUTING .md
        run: |
          npm install
          node build
      - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
